"""file type column added

Revision ID: bbd673bde2be
Revises: 
Create Date: 2025-02-28 18:51:41.431348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd673bde2be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('IFK_InvoiceLineInvoiceId', table_name='invoice_items')
    # op.drop_index('IFK_InvoiceLineTrackId', table_name='invoice_items')
    # op.drop_table('invoice_items')
    # op.drop_table('media_types')
    # op.drop_table('albums')
    # op.drop_index('IFK_InvoiceCustomerId', table_name='invoices')
    # op.drop_table('invoices')
    # op.drop_index('IFK_CustomerSupportRepId', table_name='customers')
    # op.drop_table('customers')
    # op.drop_table('genres')
    # op.drop_table('artists')
    # op.drop_index('IFK_EmployeeReportsTo', table_name='employees')
    # op.drop_table('employees')
    # op.drop_index('IFK_TrackAlbumId', table_name='tracks')
    # op.drop_index('IFK_TrackGenreId', table_name='tracks')
    # op.drop_index('IFK_TrackMediaTypeId', table_name='tracks')
    # op.drop_table('tracks')
    op.add_column('file', sa.Column('file_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_type')
    op.create_table('tracks',
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('AlbumId', sa.INTEGER(), nullable=True),
    sa.Column('MediaTypeId', sa.INTEGER(), nullable=False),
    sa.Column('GenreId', sa.INTEGER(), nullable=True),
    sa.Column('Composer', sa.NVARCHAR(length=220), nullable=True),
    sa.Column('Milliseconds', sa.INTEGER(), nullable=False),
    sa.Column('Bytes', sa.INTEGER(), nullable=True),
    sa.Column('UnitPrice', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['AlbumId'], ['albums.AlbumId'], ),
    sa.ForeignKeyConstraint(['GenreId'], ['genres.GenreId'], ),
    sa.ForeignKeyConstraint(['MediaTypeId'], ['media_types.MediaTypeId'], ),
    sa.PrimaryKeyConstraint('TrackId')
    )
    op.create_index('IFK_TrackMediaTypeId', 'tracks', ['MediaTypeId'], unique=False)
    op.create_index('IFK_TrackGenreId', 'tracks', ['GenreId'], unique=False)
    op.create_index('IFK_TrackAlbumId', 'tracks', ['AlbumId'], unique=False)
    op.create_table('employees',
    sa.Column('EmployeeId', sa.INTEGER(), nullable=False),
    sa.Column('LastName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Title', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ReportsTo', sa.INTEGER(), nullable=True),
    sa.Column('BirthDate', sa.DATETIME(), nullable=True),
    sa.Column('HireDate', sa.DATETIME(), nullable=True),
    sa.Column('Address', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('City', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('State', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('Country', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('PostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Phone', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Fax', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['ReportsTo'], ['employees.EmployeeId'], ),
    sa.PrimaryKeyConstraint('EmployeeId')
    )
    op.create_index('IFK_EmployeeReportsTo', 'employees', ['ReportsTo'], unique=False)
    op.create_table('artists',
    sa.Column('ArtistId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('ArtistId')
    )
    op.create_table('genres',
    sa.Column('GenreId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('GenreId')
    )
    op.create_table('customers',
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('LastName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Company', sa.NVARCHAR(length=80), nullable=True),
    sa.Column('Address', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('City', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('State', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('Country', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('PostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Phone', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Fax', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=60), nullable=False),
    sa.Column('SupportRepId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['SupportRepId'], ['employees.EmployeeId'], ),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    op.create_index('IFK_CustomerSupportRepId', 'customers', ['SupportRepId'], unique=False)
    op.create_table('invoices',
    sa.Column('InvoiceId', sa.INTEGER(), nullable=False),
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('InvoiceDate', sa.DATETIME(), nullable=False),
    sa.Column('BillingAddress', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('BillingCity', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingState', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingCountry', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingPostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['customers.CustomerId'], ),
    sa.PrimaryKeyConstraint('InvoiceId')
    )
    op.create_index('IFK_InvoiceCustomerId', 'invoices', ['CustomerId'], unique=False)
    op.create_table('albums',
    sa.Column('AlbumId', sa.INTEGER(), nullable=False),
    sa.Column('Title', sa.NVARCHAR(length=160), nullable=False),
    sa.Column('ArtistId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ArtistId'], ['artists.ArtistId'], ),
    sa.PrimaryKeyConstraint('AlbumId')
    )
    op.create_table('media_types',
    sa.Column('MediaTypeId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('MediaTypeId')
    )
    op.create_table('invoice_items',
    sa.Column('InvoiceLineId', sa.INTEGER(), nullable=False),
    sa.Column('InvoiceId', sa.INTEGER(), nullable=False),
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.Column('UnitPrice', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('Quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['InvoiceId'], ['invoices.InvoiceId'], ),
    sa.ForeignKeyConstraint(['TrackId'], ['tracks.TrackId'], ),
    sa.PrimaryKeyConstraint('InvoiceLineId')
    )
    op.create_index('IFK_InvoiceLineTrackId', 'invoice_items', ['TrackId'], unique=False)
    op.create_index('IFK_InvoiceLineInvoiceId', 'invoice_items', ['InvoiceId'], unique=False)
    # ### end Alembic commands ###
